name: Trigger Repo B workflow

on:
  push:
    branches: [main]

jobs:
  call-flake-update-workflow:
    runs-on: ubuntu-latest
    steps:
      # See: https://www.nieknijland.nl/blog/how-to-trigger-a-github-action-workflow-in-another-repository
      - name: Dispatch update-flake-lock workflow in different repos
        env:
          GH_TOKEN: ${{ secrets.DISPATCH_PAT }}
        run: |
          owner="yoquec"
          repo="dotfiles"
          workflow="update-flake-lock-nvim-input.yml"
          ref="main"
          short_sha="${GITHUB_SHA::7}"
          source_repo="github:yoquec/nvim"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${owner}/${repo}/actions/workflows/${workflow}/dispatches \
            -d "{\"ref\":\"${ref}\"}"
